// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrazalesCamilo_PruebaProgreso1.Migrations
{
    [DbContext(typeof(Pruebaprogreso1))]
    [Migration("20241030230103_Migracion 3")]
    partial class Migracion3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrazalesCamilo_PruebaProgreso1.Models.CBrazales", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<int>("Id_celular")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Salario")
                        .HasColumnType("float");

                    b.Property<bool>("Tiene_trabajo")
                        .HasColumnType("bit");

                    b.HasKey("Id_usuario");

                    b.HasIndex("Id_celular");

                    b.ToTable("CBrazales");
                });

            modelBuilder.Entity("BrazalesCamilo_PruebaProgreso1.Models.Celular", b =>
                {
                    b.Property<int>("Id_celular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_celular"));

                    b.Property<string>("CelularNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("Id_celular");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("BrazalesCamilo_PruebaProgreso1.Models.CBrazales", b =>
                {
                    b.HasOne("BrazalesCamilo_PruebaProgreso1.Models.Celular", "Celular")
                        .WithMany()
                        .HasForeignKey("Id_celular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Celular");
                });
#pragma warning restore 612, 618
        }
    }
}
